export const coupleQuestions = [
  { id: 'c-l-01', intensity: 'leve', category: 'Memórias', text: 'Qual foi o momento em que você percebeu que estava realmente se apaixonando por mim?' },
  { id: 'c-l-02', intensity: 'leve', category: 'Carinho', text: 'Qual pequena coisa que eu faço no dia a dia mais faz você se sentir amado(a)?' },
  { id: 'c-l-03', intensity: 'leve', category: 'Memórias', text: 'Se pudéssemos reviver um único encontro nosso exatamente como aconteceu, qual seria?' },
  { id: 'c-l-04', intensity: 'leve', category: 'Cotidiano', text: 'Qual mania minha você acha mais engraçada — e qual secretamente acha fofa?' },
  { id: 'c-l-05', intensity: 'leve', category: 'Carinho', text: 'Qual elogio meu ficou guardado na sua memória?' },
  { id: 'c-l-06', intensity: 'leve', category: 'Descobertas', text: 'O que você descobriu sobre mim depois de começarmos a ficar juntos que mais te surpreendeu?' },
  { id: 'c-l-07', intensity: 'leve', category: 'Memórias', text: 'Qual música, cheiro ou lugar faz você lembrar imediatamente da nossa história?' },
  { id: 'c-l-08', intensity: 'leve', category: 'Diversão', text: 'Qual seria o date perfeito para nós se tivéssemos uma noite livre e orçamento ilimitado?' },
  { id: 'c-l-09', intensity: 'leve', category: 'Cotidiano', text: 'Em qual situação nós dois funcionamos melhor como equipe?' },
  { id: 'c-l-10', intensity: 'leve', category: 'Carinho', text: 'Qual característica minha você gostaria que eu enxergasse em mim com os seus olhos?' },
  { id: 'c-l-11', intensity: 'leve', category: 'Diversão', text: 'Se nossa relação fosse um filme, qual seria o gênero e qual seria o título?' },
  { id: 'c-l-12', intensity: 'leve', category: 'Memórias', text: 'Qual foi a nossa melhor viagem, passeio ou aventura até hoje e por quê?' },
  { id: 'c-l-13', intensity: 'leve', category: 'Descobertas', text: 'Qual hábito meu você acabou incorporando na sua própria vida?' },
  { id: 'c-l-14', intensity: 'leve', category: 'Carinho', text: 'Que gesto simples meu sempre consegue melhorar o seu dia?' },

  { id: 'c-p-01', intensity: 'profundo', category: 'Conexão', text: 'Em quais momentos você sente que eu realmente te entendo?' },
  { id: 'c-p-02', intensity: 'profundo', category: 'Futuro', text: 'Como você imagina um dia comum da nossa vida daqui a dez anos?' },
  { id: 'c-p-03', intensity: 'profundo', category: 'Conexão', text: 'Existe algo que você gostaria de conseguir me contar com mais facilidade?' },
  { id: 'c-p-04', intensity: 'profundo', category: 'Segurança', text: 'O que faz você se sentir mais seguro(a) dentro da nossa relação?' },
  { id: 'c-p-05', intensity: 'profundo', category: 'Crescimento', text: 'Em que aspecto você acha que nós mais amadurecemos como casal?' },
  { id: 'c-p-06', intensity: 'profundo', category: 'Futuro', text: 'Qual sonho seu você mais gostaria de construir comigo?' },
  { id: 'c-p-07', intensity: 'profundo', category: 'Cuidado', text: 'Quando você está mal, o que eu poderia fazer com mais frequência para te apoiar melhor?' },
  { id: 'c-p-08', intensity: 'profundo', category: 'Conexão', text: 'Qual conversa nossa mudou a forma como você enxerga a nossa relação?' },
  { id: 'c-p-09', intensity: 'profundo', category: 'Gratidão', text: 'Por qual fase difícil que atravessamos juntos você sente mais orgulho de nós?' },
  { id: 'c-p-10', intensity: 'profundo', category: 'Crescimento', text: 'Que qualidade você acha que nós despertamos um no outro?' },
  { id: 'c-p-11', intensity: 'profundo', category: 'Futuro', text: 'Que tradição só nossa você gostaria que existisse pelo resto da vida?' },
  { id: 'c-p-12', intensity: 'profundo', category: 'Conexão', text: 'Qual medo sobre o futuro fica menor quando você pensa que estaremos juntos?' },
  { id: 'c-p-13', intensity: 'profundo', category: 'Cuidado', text: 'Quando nós discordamos, o que mais ajuda você a voltar a se conectar comigo?' },
  { id: 'c-p-14', intensity: 'profundo', category: 'Gratidão', text: 'O que existe hoje na nossa vida que você gostaria de nunca tratar como algo garantido?' },

  { id: 'c-q-01', intensity: 'quente', category: 'Intimidade', text: 'O que mais faz você se sentir desejado(a) por mim?' },
  { id: 'c-q-02', intensity: 'quente', category: 'Clima', text: 'Qual tipo de clima, atitude ou momento mais aumenta a nossa conexão íntima?' },
  { id: 'c-q-03', intensity: 'quente', category: 'Preferências', text: 'Existe algum tipo de carinho ou toque não sexual que te deixa especialmente próximo(a) de mim?' },
  { id: 'c-q-04', intensity: 'quente', category: 'Comunicação', text: 'O que eu faço que ajuda você a se sentir confortável para dizer do que gosta e do que não gosta?' },
  { id: 'c-q-05', intensity: 'quente', category: 'Desejo', text: 'Qual lembrança romântica ou íntima nossa ainda faz você sorrir quando pensa nela?' },
  { id: 'c-q-06', intensity: 'quente', category: 'Clima', text: 'Qual seria a noite romântica perfeita para criar um clima só nosso?' },
  { id: 'c-q-07', intensity: 'quente', category: 'Preferências', text: 'Você prefere mais espontaneidade ou mais antecipação quando queremos criar um momento especial?' },
  { id: 'c-q-08', intensity: 'quente', category: 'Desejo', text: 'Qual elogio vindo de mim faz você se sentir mais atraente?' },
  { id: 'c-q-09', intensity: 'quente', category: 'Comunicação', text: 'Há alguma coisa sobre intimidade que você gostaria que conversássemos com mais naturalidade?' },
  { id: 'c-q-10', intensity: 'quente', category: 'Conexão', text: 'O que diferencia, para você, um momento apenas romântico de um momento realmente íntimo?' },
  { id: 'c-q-11', intensity: 'quente', category: 'Desejo', text: 'Qual atitude minha durante um encontro faz você sentir mais química entre nós?' },
  { id: 'c-q-12', intensity: 'quente', category: 'Preferências', text: 'Se pudéssemos planejar uma escapada romântica de 24 horas, onde seria e como você imaginaria esse tempo juntos?' },
  { id: 'c-q-13', intensity: 'quente', category: 'Conexão', text: 'Em quais momentos você sente que nossa intimidade emocional e nossa atração ficam mais conectadas?' },
  { id: 'c-q-14', intensity: 'quente', category: 'Cuidado', text: 'O que faz você se sentir mais respeitado(a), seguro(a) e à vontade nos nossos momentos íntimos?' }
];

export const triviaQuestions = [
  { id: 't-e-01', difficulty: 'easy', category: 'Geografia', prompt: 'Qual é a capital da Argentina?', options: ['Córdoba', 'Buenos Aires', 'Rosário', 'Mendoza'], answer: 1 },
  { id: 't-e-02', difficulty: 'easy', category: 'Ciência', prompt: 'Qual planeta é conhecido como Planeta Vermelho?', options: ['Vênus', 'Júpiter', 'Marte', 'Mercúrio'], answer: 2 },
  { id: 't-e-03', difficulty: 'easy', category: 'História', prompt: 'Em qual país ficam as pirâmides de Gizé?', options: ['México', 'Egito', 'Peru', 'Índia'], answer: 1 },
  { id: 't-e-04', difficulty: 'easy', category: 'Tecnologia', prompt: 'O que significa a sigla CPU?', options: ['Central Processing Unit', 'Computer Personal Utility', 'Core Program User', 'Central Power Usage'], answer: 0 },
  { id: 't-e-05', difficulty: 'easy', category: 'Cinema', prompt: 'Qual personagem vive em uma casa-abacaxi no fundo do mar?', options: ['Patrick', 'Bob Esponja', 'Nemo', 'Popeye'], answer: 1 },
  { id: 't-e-06', difficulty: 'easy', category: 'Natureza', prompt: 'Qual é o maior animal terrestre atualmente?', options: ['Girafa', 'Rinoceronte', 'Elefante-africano', 'Hipopótamo'], answer: 2 },
  { id: 't-e-07', difficulty: 'easy', category: 'Esportes', prompt: 'Quantos jogadores de cada time começam uma partida de futebol em campo?', options: ['9', '10', '11', '12'], answer: 2 },
  { id: 't-e-08', difficulty: 'easy', category: 'Música', prompt: 'Qual instrumento normalmente possui teclas pretas e brancas?', options: ['Violino', 'Piano', 'Trompete', 'Bateria'], answer: 1 },
  { id: 't-e-09', difficulty: 'easy', category: 'Geografia', prompt: 'Em qual continente fica o Japão?', options: ['Europa', 'África', 'Ásia', 'Oceania'], answer: 2 },
  { id: 't-e-10', difficulty: 'easy', category: 'Ciência', prompt: 'Qual gás as plantas absorvem principalmente da atmosfera durante a fotossíntese?', options: ['Oxigênio', 'Nitrogênio', 'Dióxido de carbono', 'Hélio'], answer: 2 },
  { id: 't-e-11', difficulty: 'easy', category: 'Cultura', prompt: 'Qual destas festas é tradicionalmente celebrada no Brasil com quadrilhas e comidas típicas?', options: ['Oktoberfest', 'Festa Junina', 'Hanami', 'Ação de Graças'], answer: 1 },
  { id: 't-e-12', difficulty: 'easy', category: 'Matemática', prompt: 'Quanto é 12 × 8?', options: ['86', '92', '96', '108'], answer: 2 },
  { id: 't-e-13', difficulty: 'easy', category: 'Literatura', prompt: 'Quem escreveu “Romeu e Julieta”?', options: ['William Shakespeare', 'Charles Dickens', 'Machado de Assis', 'Miguel de Cervantes'], answer: 0 },
  { id: 't-e-14', difficulty: 'easy', category: 'Corpo Humano', prompt: 'Qual órgão bombeia sangue para o corpo?', options: ['Pulmão', 'Fígado', 'Coração', 'Rim'], answer: 2 },
  { id: 't-e-15', difficulty: 'easy', category: 'Geografia', prompt: 'Qual oceano banha a maior parte da costa brasileira?', options: ['Pacífico', 'Atlântico', 'Índico', 'Ártico'], answer: 1 },
  { id: 't-e-16', difficulty: 'easy', category: 'Tecnologia', prompt: 'Qual destes é um navegador de internet?', options: ['Chrome', 'Excel', 'Photoshop', 'Spotify'], answer: 0 },
  { id: 't-e-17', difficulty: 'easy', category: 'Natureza', prompt: 'Quantas patas tem uma aranha?', options: ['6', '8', '10', '12'], answer: 1 },
  { id: 't-e-18', difficulty: 'easy', category: 'História', prompt: 'Quem foi o primeiro homem a pisar na Lua?', options: ['Yuri Gagarin', 'Buzz Aldrin', 'Neil Armstrong', 'John Glenn'], answer: 2 },

  { id: 't-m-01', difficulty: 'medium', category: 'Geografia', prompt: 'Qual país possui a maior área territorial do mundo?', options: ['Canadá', 'China', 'Estados Unidos', 'Rússia'], answer: 3 },
  { id: 't-m-02', difficulty: 'medium', category: 'Ciência', prompt: 'Qual elemento químico possui o símbolo Fe?', options: ['Flúor', 'Ferro', 'Fósforo', 'Frâncio'], answer: 1 },
  { id: 't-m-03', difficulty: 'medium', category: 'História', prompt: 'A queda do Muro de Berlim ocorreu em qual ano?', options: ['1979', '1985', '1989', '1993'], answer: 2 },
  { id: 't-m-04', difficulty: 'medium', category: 'Tecnologia', prompt: 'Qual protocolo é usado para traduzir nomes de domínio em endereços IP?', options: ['DNS', 'SSH', 'SMTP', 'FTP'], answer: 0 },
  { id: 't-m-05', difficulty: 'medium', category: 'Literatura', prompt: 'Quem escreveu “Dom Casmurro”?', options: ['José de Alencar', 'Machado de Assis', 'Carlos Drummond de Andrade', 'Jorge Amado'], answer: 1 },
  { id: 't-m-06', difficulty: 'medium', category: 'Ciência', prompt: 'Qual é a unidade de medida da resistência elétrica?', options: ['Volt', 'Ampere', 'Ohm', 'Watt'], answer: 2 },
  { id: 't-m-07', difficulty: 'medium', category: 'Geografia', prompt: 'Qual é o maior deserto quente do mundo?', options: ['Saara', 'Atacama', 'Gobi', 'Kalahari'], answer: 0 },
  { id: 't-m-08', difficulty: 'medium', category: 'Artes', prompt: 'Quem pintou “A Noite Estrelada”?', options: ['Claude Monet', 'Vincent van Gogh', 'Pablo Picasso', 'Salvador Dalí'], answer: 1 },
  { id: 't-m-09', difficulty: 'medium', category: 'Esportes', prompt: 'Em uma partida oficial de vôlei de quadra, quantos jogadores por equipe ficam em quadra?', options: ['5', '6', '7', '8'], answer: 1 },
  { id: 't-m-10', difficulty: 'medium', category: 'Biologia', prompt: 'Qual estrutura celular contém a maior parte do material genético de uma célula humana?', options: ['Ribossomo', 'Lisossomo', 'Núcleo', 'Complexo de Golgi'], answer: 2 },
  { id: 't-m-11', difficulty: 'medium', category: 'Cinema', prompt: 'Quem dirigiu o filme “Titanic”, lançado em 1997?', options: ['Steven Spielberg', 'James Cameron', 'Ridley Scott', 'Peter Jackson'], answer: 1 },
  { id: 't-m-12', difficulty: 'medium', category: 'Matemática', prompt: 'Qual é a raiz quadrada de 144?', options: ['10', '11', '12', '14'], answer: 2 },
  { id: 't-m-13', difficulty: 'medium', category: 'História', prompt: 'Qual civilização construiu Machu Picchu?', options: ['Maia', 'Asteca', 'Inca', 'Olmeca'], answer: 2 },
  { id: 't-m-14', difficulty: 'medium', category: 'Música', prompt: 'Qual banda lançou o álbum “The Dark Side of the Moon”?', options: ['Led Zeppelin', 'Pink Floyd', 'The Who', 'Queen'], answer: 1 },
  { id: 't-m-15', difficulty: 'medium', category: 'Geografia', prompt: 'Qual rio atravessa a cidade de Paris?', options: ['Tâmisa', 'Sena', 'Danúbio', 'Reno'], answer: 1 },
  { id: 't-m-16', difficulty: 'medium', category: 'Tecnologia', prompt: 'Em segurança da informação, qual propriedade garante que dados não foram alterados indevidamente?', options: ['Disponibilidade', 'Integridade', 'Escalabilidade', 'Latência'], answer: 1 },
  { id: 't-m-17', difficulty: 'medium', category: 'Ciência', prompt: 'Qual é o nome do processo em que um sólido passa diretamente para o estado gasoso?', options: ['Condensação', 'Fusão', 'Sublimação', 'Vaporização'], answer: 2 },
  { id: 't-m-18', difficulty: 'medium', category: 'Cultura', prompt: 'Em qual cidade italiana fica o Coliseu?', options: ['Milão', 'Roma', 'Florença', 'Nápoles'], answer: 1 },

  { id: 't-h-01', difficulty: 'hard', category: 'Ciência', prompt: 'Qual partícula subatômica possui carga elétrica negativa?', options: ['Próton', 'Nêutron', 'Elétron', 'Pósitron'], answer: 2 },
  { id: 't-h-02', difficulty: 'hard', category: 'História', prompt: 'Qual tratado encerrou formalmente a Primeira Guerra Mundial entre a Alemanha e os Aliados?', options: ['Tratado de Utrecht', 'Tratado de Versalhes', 'Tratado de Tordesilhas', 'Tratado de Viena'], answer: 1 },
  { id: 't-h-03', difficulty: 'hard', category: 'Geografia', prompt: 'Qual estreito separa a Ásia da América do Norte?', options: ['Bósforo', 'Gibraltar', 'Bering', 'Ormuz'], answer: 2 },
  { id: 't-h-04', difficulty: 'hard', category: 'Tecnologia', prompt: 'Qual estrutura de dados opera tipicamente no princípio LIFO?', options: ['Fila', 'Pilha', 'Árvore B', 'Grafo'], answer: 1 },
  { id: 't-h-05', difficulty: 'hard', category: 'Literatura', prompt: 'Quem escreveu “Cem Anos de Solidão”?', options: ['Jorge Luis Borges', 'Gabriel García Márquez', 'Mario Vargas Llosa', 'Pablo Neruda'], answer: 1 },
  { id: 't-h-06', difficulty: 'hard', category: 'Química', prompt: 'Qual é o número atômico do carbono?', options: ['4', '6', '8', '12'], answer: 1 },
  { id: 't-h-07', difficulty: 'hard', category: 'Astronomia', prompt: 'Qual é a maior lua de Saturno?', options: ['Europa', 'Titã', 'Ganímedes', 'Io'], answer: 1 },
  { id: 't-h-08', difficulty: 'hard', category: 'História', prompt: 'Qual império tinha Constantinopla como capital antes da conquista otomana de 1453?', options: ['Bizantino', 'Carolíngio', 'Sacro Romano', 'Aquemênida'], answer: 0 },
  { id: 't-h-09', difficulty: 'hard', category: 'Geografia', prompt: 'Qual é a capital da Mongólia?', options: ['Astana', 'Bishkek', 'Ulaanbaatar', 'Tashkent'], answer: 2 },
  { id: 't-h-10', difficulty: 'hard', category: 'Música', prompt: 'Quantas semitons existem em uma oitava no sistema temperado ocidental?', options: ['8', '10', '12', '14'], answer: 2 },
  { id: 't-h-11', difficulty: 'hard', category: 'Biologia', prompt: 'Qual organela é conhecida como principal responsável pela produção de ATP em células eucarióticas?', options: ['Mitocôndria', 'Ribossomo', 'Peroxissomo', 'Centríolo'], answer: 0 },
  { id: 't-h-12', difficulty: 'hard', category: 'Matemática', prompt: 'Qual é o valor aproximado de π com duas casas decimais?', options: ['2,72', '3,14', '1,62', '3,41'], answer: 1 },
  { id: 't-h-13', difficulty: 'hard', category: 'Artes', prompt: 'O movimento artístico associado a Claude Monet é conhecido principalmente como:', options: ['Cubismo', 'Surrealismo', 'Impressionismo', 'Futurismo'], answer: 2 },
  { id: 't-h-14', difficulty: 'hard', category: 'Tecnologia', prompt: 'Qual algoritmo de hash pertence à família SHA-2?', options: ['MD5', 'SHA-256', 'CRC32', 'DES'], answer: 1 },
  { id: 't-h-15', difficulty: 'hard', category: 'Ciência', prompt: 'Qual escala mede a dureza relativa de minerais?', options: ['Kelvin', 'Mohs', 'Richter', 'Beaufort'], answer: 1 },
  { id: 't-h-16', difficulty: 'hard', category: 'Geografia', prompt: 'Qual país africano é completamente cercado pela África do Sul?', options: ['Eswatini', 'Lesoto', 'Botsuana', 'Namíbia'], answer: 1 },
  { id: 't-h-17', difficulty: 'hard', category: 'História', prompt: 'Quem comandou a expedição portuguesa que chegou ao Brasil em 1500?', options: ['Vasco da Gama', 'Bartolomeu Dias', 'Pedro Álvares Cabral', 'Fernão de Magalhães'], answer: 2 },
  { id: 't-h-18', difficulty: 'hard', category: 'Tecnologia', prompt: 'Qual porta TCP é tradicionalmente associada ao HTTPS?', options: ['22', '53', '80', '443'], answer: 3 }
];

export const dares = [
  { id: 'd-01', level: 'leve', text: 'Faça um discurso de 20 segundos agradecendo por ter perdido como se tivesse ganhado um Oscar.' },
  { id: 'd-02', level: 'leve', text: 'Cante o refrão de uma música escolhida pelos vencedores.' },
  { id: 'd-03', level: 'leve', text: 'Imite um personagem famoso até alguém adivinhar quem é.' },
  { id: 'd-04', level: 'leve', text: 'Conte a pior piada que conseguir inventar agora.' },
  { id: 'd-05', level: 'leve', text: 'Fale por 30 segundos como narrador de futebol descrevendo tudo o que está acontecendo na sala.' },
  { id: 'd-06', level: 'leve', text: 'Faça uma pose dramática para uma foto que o grupo escolher.' },
  { id: 'd-07', level: 'leve', text: 'Tente vender um objeto aleatório da sala como se fosse um produto revolucionário.' },
  { id: 'd-08', level: 'leve', text: 'Dance por 20 segundos sem música.' },
  { id: 'd-09', level: 'leve', text: 'Fale seu nome como se fosse um vilão revelando sua identidade secreta.' },
  { id: 'd-10', level: 'leve', text: 'Invente um slogan publicitário para a pessoa ou casal vencedor.' },
  { id: 'd-11', level: 'engraçado', text: 'Faça uma imitação de alguém do grupo com carinho, sem revelar quem é, até acertarem.' },
  { id: 'd-12', level: 'engraçado', text: 'Fale durante um minuto usando uma voz completamente diferente da sua.' },
  { id: 'd-13', level: 'engraçado', text: 'Faça uma passarela de moda improvisada usando um objeto da sala como acessório.' },
  { id: 'd-14', level: 'engraçado', text: 'Crie uma coreografia de 15 segundos e ensine ao grupo.' },
  { id: 'd-15', level: 'engraçado', text: 'Faça uma declaração de amor exageradamente dramática para um objeto escolhido pelo grupo.' },
  { id: 'd-16', level: 'engraçado', text: 'Explique como fazer um café como se estivesse apresentando uma teoria científica revolucionária.' },
  { id: 'd-17', level: 'engraçado', text: 'Faça três sons de animais; o grupo precisa acertar pelo menos dois.' },
  { id: 'd-18', level: 'engraçado', text: 'Narre sua própria derrota como se fosse o trailer épico de um filme.' },
  { id: 'd-19', level: 'engraçado', text: 'Faça uma entrevista consigo mesmo: uma pergunta e uma resposta em personagens diferentes.' },
  { id: 'd-20', level: 'engraçado', text: 'Invente um jingle de cinco segundos com a palavra “derrota”.' },
  { id: 'd-21', level: 'ousado', text: 'Deixe os vencedores escolherem uma música e faça uma performance de 30 segundos.' },
  { id: 'd-22', level: 'ousado', text: 'Conte uma história verdadeira e engraçada sua que o grupo ainda não conhece.' },
  { id: 'd-23', level: 'ousado', text: 'Faça uma cantada propositalmente horrível para alguém que concordar em participar da brincadeira.' },
  { id: 'd-24', level: 'ousado', text: 'Recrie uma cena de novela improvisada com outra pessoa voluntária.' },
  { id: 'd-25', level: 'ousado', text: 'Faça cinco agachamentos enquanto canta parabéns em ritmo de ópera.' },
  { id: 'd-26', level: 'ousado', text: 'Deixe o grupo escolher três palavras e improvise uma música curta usando todas elas.' },
  { id: 'd-27', level: 'ousado', text: 'Faça uma previsão absurda do futuro de cada jogador em uma frase.' },
  { id: 'd-28', level: 'ousado', text: 'Imite uma cena de pedido de casamento para um objeto da sala.' },
  { id: 'd-29', level: 'ousado', text: 'Faça um tutorial de 30 segundos ensinando algo que claramente não precisa de tutorial.' },
  { id: 'd-30', level: 'ousado', text: 'Faça uma foto de “capa de álbum” escolhendo pose e título na hora.' }
];

export const difficultyLabels = {
  mixed: 'Mista',
  easy: 'Fácil',
  medium: 'Média',
  hard: 'Difícil'
};

export const intensityLabels = {
  leve: 'Leve',
  profundo: 'Profundo',
  quente: 'Quente'
};
