export const eroticCoupleQuestions = [
  { id: 'c-e-01', intensity: 'erotico', category: 'Desejo sexual', text: 'O que faz você sentir mais desejo sexual por mim hoje, comparado ao começo da relação?' },
  { id: 'c-e-02', intensity: 'erotico', category: 'Desejo sexual', text: 'Em quais momentos você percebe que está com vontade de transar, mas acaba não demonstrando?' },
  { id: 'c-e-03', intensity: 'erotico', category: 'Desejo sexual', text: 'Você sente que nosso desejo acontece no mesmo ritmo ou cada um funciona de um jeito diferente?' },
  { id: 'c-e-04', intensity: 'erotico', category: 'Frequência', text: 'Se pudéssemos ajustar nossa frequência sexual sem culpa nem cobrança, o que seria ideal para você?' },
  { id: 'c-e-05', intensity: 'erotico', category: 'Frequência', text: 'Quando passamos mais tempo sem sexo, o que você sente falta primeiro: do contato, da excitação, da conexão ou de outra coisa?' },
  { id: 'c-e-06', intensity: 'erotico', category: 'Iniciativa', text: 'Você sente que existe equilíbrio entre quem inicia o sexo ou gostaria que isso mudasse?' },
  { id: 'c-e-07', intensity: 'erotico', category: 'Iniciativa', text: 'Qual é a maneira mais confortável para você dizer que quer sexo sem medo de rejeição?' },
  { id: 'c-e-08', intensity: 'erotico', category: 'Rejeição', text: 'Quando um de nós não está com vontade, como podemos lidar com isso sem transformar o momento em insegurança ou pressão?' },
  { id: 'c-e-09', intensity: 'erotico', category: 'Prazer', text: 'Você sente que consegue me dizer com clareza o que aumenta seu prazer durante o sexo?' },
  { id: 'c-e-10', intensity: 'erotico', category: 'Prazer', text: 'Existe algo que fazemos no sexo que você gosta muito e acha que eu talvez não perceba o quanto é importante para você?' },
  { id: 'c-e-11', intensity: 'erotico', category: 'Orgasmo', text: 'Você sente alguma pressão para chegar ao orgasmo durante o sexo? O que tornaria essa experiência mais leve?' },
  { id: 'c-e-12', intensity: 'erotico', category: 'Orgasmo', text: 'Para você, um encontro sexual pode ser ótimo mesmo sem orgasmo? O que define que valeu a pena?' },
  { id: 'c-e-13', intensity: 'erotico', category: 'Orgasmo', text: 'Existe alguma coisa sobre seu orgasmo ou sobre como você chega ao prazer que gostaria de conseguir explicar melhor para mim?' },
  { id: 'c-e-14', intensity: 'erotico', category: 'Corpo', text: 'Existe alguma insegurança com seu corpo que aparece durante o sexo e que você gostaria que eu soubesse tratar melhor?' },
  { id: 'c-e-15', intensity: 'erotico', category: 'Corpo', text: 'O que eu posso fazer para você se sentir mais desejado(a) e confortável com seu corpo nos nossos momentos sexuais?' },
  { id: 'c-e-16', intensity: 'erotico', category: 'Sexo oral', text: 'Como você se sente em conversar abertamente sobre preferências, limites e conforto relacionados a sexo oral?' },
  { id: 'c-e-17', intensity: 'erotico', category: 'Práticas', text: 'Existe alguma prática sexual que você gosta, mas gostaria que fizéssemos de um jeito diferente?' },
  { id: 'c-e-18', intensity: 'erotico', category: 'Práticas', text: 'Há alguma prática sexual que para você entra claramente em “sim”, “talvez” ou “não” e que valeria conversarmos melhor?' },
  { id: 'c-e-19', intensity: 'erotico', category: 'Práticas', text: 'Como você se sente em conversar sobre sexo anal como possibilidade, limite ou simplesmente algo que não interessa?' },
  { id: 'c-e-20', intensity: 'erotico', category: 'Brinquedos', text: 'Você gostaria que brinquedos sexuais fizessem parte da nossa intimidade com mais naturalidade?' },
  { id: 'c-e-21', intensity: 'erotico', category: 'Brinquedos', text: 'Se fôssemos escolher um brinquedo sexual juntos, o que precisaria acontecer para isso parecer divertido e não constrangedor?' },
  { id: 'c-e-22', intensity: 'erotico', category: 'Masturbação', text: 'Qual espaço você acha saudável para masturbação individual dentro de uma relação?' },
  { id: 'c-e-23', intensity: 'erotico', category: 'Masturbação', text: 'Você se sentiria confortável falando comigo sobre como você se masturba e o que aprende sobre seu próprio prazer?' },
  { id: 'c-e-24', intensity: 'erotico', category: 'Pornografia', text: 'Pornografia tem algum papel positivo, neutro ou negativo na forma como você vive sua sexualidade hoje?' },
  { id: 'c-e-25', intensity: 'erotico', category: 'Pornografia', text: 'Que acordos sobre pornografia fariam você se sentir respeitado(a) e seguro(a) dentro da relação?' },
  { id: 'c-e-26', intensity: 'erotico', category: 'Fantasia', text: 'Existe alguma fantasia sexual que você nunca realizou e que gostaria de poder contar sem que isso vire uma obrigação?' },
  { id: 'c-e-27', intensity: 'erotico', category: 'Fantasia', text: 'Qual fantasia você prefere manter apenas na imaginação, mesmo que ela seja excitante para você?' },
  { id: 'c-e-28', intensity: 'erotico', category: 'Fetiches', text: 'Existe algum fetiche seu que você gostaria que eu compreendesse melhor antes de decidir se toparíamos explorar juntos?' },
  { id: 'c-e-29', intensity: 'erotico', category: 'Fetiches', text: 'Existe algum fetiche meu que você teria curiosidade de conhecer melhor, mesmo sem prometer experimentar?' },
  { id: 'c-e-30', intensity: 'erotico', category: 'BDSM', text: 'Dominação, submissão, comandos ou restrições consensuais despertam curiosidade em você? O que seria indispensável combinar antes?' },
  { id: 'c-e-31', intensity: 'erotico', category: 'BDSM', text: 'Você se sentiria confortável usando palavra de segurança e combinando limites claros em uma experiência mais intensa?' },
  { id: 'c-e-32', intensity: 'erotico', category: 'Terceiros', text: 'Como você se sente ao falar sobre fantasias que envolvem outras pessoas, mesmo quando elas não seriam realizadas na vida real?' },
  { id: 'c-e-33', intensity: 'erotico', category: 'Terceiros', text: 'Existe algum cenário envolvendo terceiros que para você é fantasia, possibilidade negociável ou limite absoluto?' },
  { id: 'c-e-34', intensity: 'erotico', category: 'Exclusividade', text: 'O que exclusividade sexual significa para você além de simplesmente “não transar com outras pessoas”?' },
  { id: 'c-e-35', intensity: 'erotico', category: 'Comunicação', text: 'Qual assunto sexual você ainda acha difícil conversar comigo sem sentir vergonha, medo de julgamento ou insegurança?' },
  { id: 'c-e-36', intensity: 'erotico', category: 'Comunicação', text: 'Durante o sexo, você prefere orientações diretas sobre o que está bom ou sinais mais sutis?' },
  { id: 'c-e-37', intensity: 'erotico', category: 'Limites', text: 'Existe algum limite sexual que mudou ao longo da sua vida e que hoje você enxerga de outra forma?' },
  { id: 'c-e-38', intensity: 'erotico', category: 'Limites', text: 'Que tipo de conversa precisa acontecer antes de você se sentir seguro(a) para experimentar algo sexual novo?' },
  { id: 'c-e-39', intensity: 'erotico', category: 'Depois do sexo', text: 'O que você mais precisa emocionalmente depois do sexo: carinho, conversa, espaço, humor, descanso ou outra coisa?' },
  { id: 'c-e-40', intensity: 'erotico', category: 'Intimidade', text: 'O que você gostaria que nossa vida sexual tivesse mais daqui para frente: liberdade, novidade, frequência, profundidade, segurança ou espontaneidade?' }
];
