export const eroticCoupleQuestions = [
  { id: 'c-e-01', intensity: 'erotico', category: 'Desejo sexual', text: 'O que faz você sentir mais desejo sexual por mim hoje, comparado ao começo da relação?' },
  { id: 'c-e-02', intensity: 'erotico', category: 'Desejo sexual', text: 'Em quais momentos você percebe que está com vontade de transar, mas acaba não demonstrando?' },
  { id: 'c-e-03', intensity: 'erotico', category: 'Desejo sexual', text: 'Você sente que nosso desejo acontece no mesmo ritmo ou cada um funciona de um jeito diferente?' },
  { id: 'c-e-04', intensity: 'erotico', category: 'Frequência', text: 'Se pudéssemos ajustar nossa frequência sexual sem culpa nem cobrança, o que seria ideal para você?' },
  { id: 'c-e-05', intensity: 'erotico', category: 'Frequência', text: 'Quando passamos mais tempo sem sexo, o que você sente falta primeiro: do contato, da excitação, da conexão ou de outra coisa?' },
  { id: 'c-e-06', intensity: 'erotico', category: 'Iniciativa', text: 'Você sente que existe equilíbrio entre quem inicia o sexo ou gostaria que isso mudasse?' },
  { id: 'c-e-07', intensity: 'erotico', category: 'Iniciativa', text: 'Qual é a maneira mais confortável para você dizer que quer sexo sem medo de rejeição?' },
  { id: 'c-e-08', intensity: 'erotico', category: 'Rejeição', text: 'Quando um de nós não está com vontade, como podemos lidar com isso sem transformar o momento em insegurança ou pressão?' },
  { id: 'c-e-09', intensity: 'erotico', category: 'Prazer', text: 'Você sente que consegue me dizer com clareza o que aumenta seu prazer durante o sexo?' },
  { id: 'c-e-10', intensity: 'erotico', category: 'Prazer', text: 'Existe algo que fazemos no sexo que você gosta muito e acha que eu talvez não perceba o quanto é importante para você?' },
  { id: 'c-e-11', intensity: 'erotico', category: 'Orgasmo', text: 'Você sente alguma pressão para chegar ao orgasmo durante o sexo? O que tornaria essa experiência mais leve?' },
  { id: 'c-e-12', intensity: 'erotico', category: 'Orgasmo', text: 'Para você, um encontro sexual pode ser ótimo mesmo sem orgasmo? O que define que valeu a pena?' },
  { id: 'c-e-13', intensity: 'erotico', category: 'Orgasmo', text: 'Existe alguma coisa sobre seu orgasmo ou sobre como você chega ao prazer que gostaria de conseguir explicar melhor para mim?' },
  { id: 'c-e-14', intensity: 'erotico', category: 'Corpo', text: 'Existe alguma insegurança com seu corpo que aparece durante o sexo e que você gostaria que eu soubesse tratar melhor?' },
  { id: 'c-e-15', intensity: 'erotico', category: 'Corpo', text: 'O que eu posso fazer para você se sentir mais desejado(a) e confortável com seu corpo nos nossos momentos sexuais?' },
  { id: 'c-e-16', intensity: 'erotico', category: 'Sexo oral', text: 'Como você se sente em conversar abertamente sobre preferências, limites e conforto relacionados a sexo oral?' },
  { id: 'c-e-17', intensity: 'erotico', category: 'Práticas', text: 'Existe alguma prática sexual que você gosta, mas gostaria que fizéssemos de um jeito diferente?' },
  { id: 'c-e-18', intensity: 'erotico', category: 'Práticas', text: 'Há alguma prática sexual que para você entra claramente em “sim”, “talvez” ou “não” e que valeria conversarmos melhor?' },
  { id: 'c-e-19', intensity: 'erotico', category: 'Práticas', text: 'Como você se sente em conversar sobre sexo anal como possibilidade, limite ou simplesmente algo que não interessa?' },
  { id: 'c-e-20', intensity: 'erotico', category: 'Brinquedos', text: 'Você gostaria que brinquedos sexuais fizessem parte da nossa intimidade com mais naturalidade?' },
  { id: 'c-e-21', intensity: 'erotico', category: 'Brinquedos', text: 'Se fôssemos escolher um brinquedo sexual juntos, o que precisaria acontecer para isso parecer divertido e não constrangedor?' },
  { id: 'c-e-22', intensity: 'erotico', category: 'Masturbação', text: 'Qual espaço você acha saudável para masturbação individual dentro de uma relação?' },
  { id: 'c-e-23', intensity: 'erotico', category: 'Masturbação', text: 'Você se sentiria confortável falando comigo sobre como você se masturba e o que aprende sobre seu próprio prazer?' },
  { id: 'c-e-24', intensity: 'erotico', category: 'Pornografia', text: 'Pornografia tem algum papel positivo, neutro ou negativo na forma como você vive sua sexualidade hoje?' },
  { id: 'c-e-25', intensity: 'erotico', category: 'Pornografia', text: 'Que acordos sobre pornografia fariam você se sentir respeitado(a) e seguro(a) dentro da relação?' },
  { id: 'c-e-26', intensity: 'erotico', category: 'Fantasia', text: 'Existe alguma fantasia sexual que você nunca realizou e que gostaria de poder contar sem que isso vire uma obrigação?' },
  { id: 'c-e-27', intensity: 'erotico', category: 'Fantasia', text: 'Qual fantasia você prefere manter apenas na imaginação, mesmo que ela seja excitante para você?' },
  { id: 'c-e-28', intensity: 'erotico', category: 'Fetiches', text: 'Existe algum fetiche seu que você gostaria que eu compreendesse melhor antes de decidir se toparíamos explorar juntos?' },
  { id: 'c-e-29', intensity: 'erotico', category: 'Fetiches', text: 'Existe algum fetiche meu que você teria curiosidade de conhecer melhor, mesmo sem prometer experimentar?' },
  { id: 'c-e-30', intensity: 'erotico', category: 'BDSM', text: 'Dominação, submissão, comandos ou restrições consensuais despertam curiosidade em você? O que seria indispensável combinar antes?' },
  { id: 'c-e-31', intensity: 'erotico', category: 'BDSM', text: 'Você se sentiria confortável usando palavra de segurança e combinando limites claros em uma experiência mais intensa?' },
  { id: 'c-e-32', intensity: 'erotico', category: 'Terceiros', text: 'Como você se sente ao falar sobre fantasias que envolvem outras pessoas, mesmo quando elas não seriam realizadas na vida real?' },
  { id: 'c-e-33', intensity: 'erotico', category: 'Terceiros', text: 'Existe algum cenário envolvendo terceiros que para você é fantasia, possibilidade negociável ou limite absoluto?' },
  { id: 'c-e-34', intensity: 'erotico', category: 'Exclusividade', text: 'O que exclusividade sexual significa para você além de simplesmente “não transar com outras pessoas”?' },
  { id: 'c-e-35', intensity: 'erotico', category: 'Comunicação', text: 'Qual assunto sexual você ainda acha difícil conversar comigo sem sentir vergonha, medo de julgamento ou insegurança?' },
  { id: 'c-e-36', intensity: 'erotico', category: 'Comunicação', text: 'Durante o sexo, você prefere orientações diretas sobre o que está bom ou sinais mais sutis?' },
  { id: 'c-e-37', intensity: 'erotico', category: 'Limites', text: 'Existe algum limite sexual que mudou ao longo da sua vida e que hoje você enxerga de outra forma?' },
  { id: 'c-e-38', intensity: 'erotico', category: 'Limites', text: 'Que tipo de conversa precisa acontecer antes de você se sentir seguro(a) para experimentar algo sexual novo?' },
  { id: 'c-e-39', intensity: 'erotico', category: 'Depois do sexo', text: 'O que você mais precisa emocionalmente depois do sexo: carinho, conversa, espaço, humor, descanso ou outra coisa?' },
  { id: 'c-e-40', intensity: 'erotico', category: 'Intimidade', text: 'O que você gostaria que nossa vida sexual tivesse mais daqui para frente: liberdade, novidade, frequência, profundidade, segurança ou espontaneidade?' },
  { id: 'c-e-41', intensity: 'erotico', category: 'BDSM', text: 'Dentro de uma dinâmica BDSM, você sente mais curiosidade em assumir o controle, entregar o controle ou alternar entre os dois papéis?' },
  { id: 'c-e-42', intensity: 'erotico', category: 'BDSM', text: 'A ideia de bondage ou restrições consensuais desperta curiosidade em você? Quais condições fariam isso parecer seguro e confortável?' },
  { id: 'c-e-43', intensity: 'erotico', category: 'BDSM', text: 'Vendas nos olhos ou outras formas leves de limitar os sentidos aumentariam sua curiosidade ou causariam desconforto?' },
  { id: 'c-e-44', intensity: 'erotico', category: 'BDSM', text: 'Você teria interesse em uma dinâmica baseada em comandos e obediência consensual? O que faria isso funcionar para você?' },
  { id: 'c-e-45', intensity: 'erotico', category: 'BDSM', text: 'Como você se sente sobre usar regras ou pequenos protocolos combinados durante uma brincadeira de dominação e submissão?' },
  { id: 'c-e-46', intensity: 'erotico', category: 'BDSM', text: 'A ideia de recompensa e punição consensuais dentro de uma fantasia BDSM te interessa, não te interessa ou depende muito do contexto?' },
  { id: 'c-e-47', intensity: 'erotico', category: 'BDSM', text: 'Você teria curiosidade sobre impacto físico consensual em intensidade leve ou moderada? Que limites seriam indispensáveis?' },
  { id: 'c-e-48', intensity: 'erotico', category: 'BDSM', text: 'Existe alguma palavra, atitude ou dinâmica de autoridade que te faria entrar mais facilmente em um papel dominante ou submisso?' },
  { id: 'c-e-49', intensity: 'erotico', category: 'BDSM', text: 'Elogios intensos durante uma dinâmica de poder te atraem mais do que provocações ou linguagem de humilhação consensual?' },
  { id: 'c-e-50', intensity: 'erotico', category: 'BDSM', text: 'Humilhação consensual é algo que desperta curiosidade, é um limite absoluto ou depende muito da forma e do contexto?' },
  { id: 'c-e-51', intensity: 'erotico', category: 'BDSM', text: 'Que diferença existe, para você, entre uma fantasia de controle excitante e uma situação que começaria a parecer desconfortável?' },
  { id: 'c-e-52', intensity: 'erotico', category: 'BDSM', text: 'Quais seriam seus limites rígidos e quais seriam seus limites negociáveis em uma experiência BDSM?' },
  { id: 'c-e-53', intensity: 'erotico', category: 'BDSM', text: 'Você preferiria combinar uma escala de intensidade antes de uma experiência BDSM para poder ajustar o ritmo durante a brincadeira?' },
  { id: 'c-e-54', intensity: 'erotico', category: 'BDSM', text: 'Além de uma palavra de segurança, que outro sinal ou gesto seria útil para comunicar “diminua”, “continue” ou “pare”?' },
  { id: 'c-e-55', intensity: 'erotico', category: 'BDSM', text: 'Que tipo de aftercare faria você se sentir cuidado(a) depois de uma experiência emocionalmente ou fisicamente mais intensa?' },
  { id: 'c-e-56', intensity: 'erotico', category: 'BDSM', text: 'Você gostaria de conversar depois de uma experiência BDSM para dizer o que funcionou, o que não funcionou e o que deveria mudar?' },
  { id: 'c-e-57', intensity: 'erotico', category: 'BDSM', text: 'Uma dinâmica de poder só durante o sexo te interessa mais do que manter pequenos elementos dessa dinâmica fora do momento íntimo?' },
  { id: 'c-e-58', intensity: 'erotico', category: 'BDSM', text: 'Usar roupas, acessórios ou símbolos para marcar uma dinâmica dominante/submissa teria significado ou graça para você?' },
  { id: 'c-e-59', intensity: 'erotico', category: 'BDSM', text: 'Qual aspecto do BDSM você mais gostaria de entender antes de decidir se quer experimentar: controle, bondage, impacto, linguagem, regras ou aftercare?' },
  { id: 'c-e-60', intensity: 'erotico', category: 'BDSM', text: 'Se criássemos uma primeira experiência BDSM bem leve e totalmente negociada, o que precisaria acontecer para você se sentir confiante para dizer sim ou não?' },
  { id: 'c-e-61', intensity: 'erotico', category: 'Consentimento', text: 'Qual seria a melhor forma de fazermos um check-in durante um momento íntimo sem quebrar o clima?' },
  { id: 'c-e-62', intensity: 'erotico', category: 'Consentimento', text: 'Existe alguma situação em que você prefere que eu confirme claramente antes de avançarmos, mesmo que normalmente exista confiança entre nós?' },
  { id: 'c-e-63', intensity: 'erotico', category: 'Desejo sexual', text: 'Que tipo de atitude minha costuma despertar seu desejo quando você não estava pensando em sexo?' },
  { id: 'c-e-64', intensity: 'erotico', category: 'Iniciativa', text: 'Você gostaria que eu fosse mais direto(a), mais sutil ou mais imprevisível ao demonstrar desejo por você?' },
  { id: 'c-e-65', intensity: 'erotico', category: 'Antecipação', text: 'Você gosta da ideia de criar expectativa ao longo do dia antes de um momento íntimo ou prefere que tudo aconteça espontaneamente?' },
  { id: 'c-e-66', intensity: 'erotico', category: 'Ambiente', text: 'O quanto ambiente, música, iluminação ou privacidade influenciam sua vontade de se soltar sexualmente?' },
  { id: 'c-e-67', intensity: 'erotico', category: 'Roleplay', text: 'Você teria curiosidade de experimentar algum tipo de roleplay? O que faria a ideia parecer divertida em vez de artificial?' },
  { id: 'c-e-68', intensity: 'erotico', category: 'Roleplay', text: 'Roupas, personagens ou algum cenário combinado aumentariam sua curiosidade em uma fantasia a dois?' },
  { id: 'c-e-69', intensity: 'erotico', category: 'Brinquedos', text: 'Você prefere descobrir novidades sexuais juntos ou gostaria que cada um pudesse pesquisar opções e depois trazer ideias para o casal?' },
  { id: 'c-e-70', intensity: 'erotico', category: 'Sensações', text: 'Explorar sensações diferentes de forma consensual desperta curiosidade em você ou você prefere manter o que já conhece bem?' },
  { id: 'c-e-71', intensity: 'erotico', category: 'Toque', text: 'Você sente que existe algum tipo de toque ou carinho íntimo que deveria aparecer mais na nossa rotina?' },
  { id: 'c-e-72', intensity: 'erotico', category: 'BDSM', text: 'Em uma dinâmica de poder consensual, o que faria você confiar o suficiente para relaxar no papel escolhido?' },
  { id: 'c-e-73', intensity: 'erotico', category: 'BDSM', text: 'Você teria curiosidade de inverter os papéis que normalmente assumimos em uma dinâmica de dominação e submissão?' },
  { id: 'c-e-74', intensity: 'erotico', category: 'BDSM', text: 'Se bondage entrasse em uma fantasia nossa, quais limites e formas de comunicação precisariam estar combinados antes?' },
  { id: 'c-e-75', intensity: 'erotico', category: 'Aftercare', text: 'Depois de algo mais intenso, o que faria você se sentir emocionalmente seguro(a), valorizado(a) e próximo(a) de mim?' },
  { id: 'c-e-76', intensity: 'erotico', category: 'Comunicação', text: 'Você prefere falar sobre sexo antes, durante ou depois dos momentos íntimos? Em qual desses momentos se sente mais à vontade?' },
  { id: 'c-e-77', intensity: 'erotico', category: 'Linguagem', text: 'Conversas mais provocantes durante a intimidade te deixam mais à vontade, indiferente ou desconfortável?' },
  { id: 'c-e-78', intensity: 'erotico', category: 'Linguagem', text: 'Você gosta mais de receber elogios, ouvir desejo de forma direta ou prefere menos conversa durante os momentos íntimos?' },
  { id: 'c-e-79', intensity: 'erotico', category: 'Provocação', text: 'Você gosta de provocação e expectativa antes do sexo ou prefere que o desejo seja resolvido de forma mais direta?' },
  { id: 'c-e-80', intensity: 'erotico', category: 'Espontaneidade', text: 'O que faz uma situação espontânea parecer excitante para você sem virar pressão ou inconveniência?' },
  { id: 'c-e-81', intensity: 'erotico', category: 'Planejamento', text: 'Marcar um momento para intimidade parece pouco espontâneo para você ou pode ajudar a criar expectativa e presença?' },
  { id: 'c-e-82', intensity: 'erotico', category: 'Ritmo', text: 'Existe algum horário, clima ou momento do dia em que você naturalmente se sente mais aberto(a) para intimidade?' },
  { id: 'c-e-83', intensity: 'erotico', category: 'Ritmo', text: 'Você prefere momentos íntimos mais rápidos e espontâneos, mais demorados e construídos ou gosta dos dois dependendo do dia?' },
  { id: 'c-e-84', intensity: 'erotico', category: 'Novidade', text: 'Qual nível de novidade mantém nossa vida sexual interessante sem fazer parecer que precisamos estar sempre inventando algo?' },
  { id: 'c-e-85', intensity: 'erotico', category: 'Rotina', text: 'Existe alguma parte da nossa rotina sexual que funciona muito bem e que você não gostaria de mudar só por buscar novidade?' },
  { id: 'c-e-86', intensity: 'erotico', category: 'Privacidade', text: 'Quais assuntos da nossa vida sexual você considera totalmente privados e não gostaria que fossem compartilhados com outras pessoas?' },
  { id: 'c-e-87', intensity: 'erotico', category: 'Privacidade', text: 'Se algum dia fizéssemos fotos ou vídeos íntimos, quais regras de consentimento, armazenamento e exclusão seriam obrigatórias para você?' },
  { id: 'c-e-88', intensity: 'erotico', category: 'Exibicionismo', text: 'A ideia de exibicionismo consensual em contexto privado desperta curiosidade, desconforto ou nenhuma reação em você?' },
  { id: 'c-e-89', intensity: 'erotico', category: 'Voyeurismo', text: 'Voyeurismo consensual dentro de limites combinados desperta alguma curiosidade em você ou é algo que prefere deixar fora da relação?' },
  { id: 'c-e-90', intensity: 'erotico', category: 'Pornografia', text: 'Assistir conteúdo adulto juntos seria algo interessante, indiferente ou desconfortável para você? Que limites seriam importantes?' },
  { id: 'c-e-91', intensity: 'erotico', category: 'Masturbação', text: 'Você acha que compartilhar mais sobre prazer individual poderia melhorar nossa intimidade ou prefere manter essa parte mais privada?' },
  { id: 'c-e-92', intensity: 'erotico', category: 'Fantasia', text: 'Você gostaria que tivéssemos um espaço sem julgamento para contar fantasias que não necessariamente queremos realizar?' },
  { id: 'c-e-93', intensity: 'erotico', category: 'Ciúme', text: 'Quando uma fantasia envolve outras pessoas, o que diferencia curiosidade imaginária de algo que poderia despertar ciúme em você?' },
  { id: 'c-e-94', intensity: 'erotico', category: 'Exclusividade', text: 'Você acha importante conversar sobre limites de exclusividade mesmo quando os dois acreditam já saber o que o outro considera aceitável?' },
  { id: 'c-e-95', intensity: 'erotico', category: 'BDSM', text: 'Você se sentiria mais seguro(a) em explorar algo intenso se tivéssemos uma palavra de segurança e também uma forma de indicar “reduza a intensidade”?' },
  { id: 'c-e-96', intensity: 'erotico', category: 'Limites', text: 'Você toparia montar comigo uma lista de “sim”, “talvez” e “não” para temas sexuais, sem obrigação de transformar os “talvez” em experiências?' },
  { id: 'c-e-97', intensity: 'erotico', category: 'Corpo', text: 'O que faz você se sentir mais confiante e desejado(a) no próprio corpo quando estamos íntimos?' },
  { id: 'c-e-98', intensity: 'erotico', category: 'Depois do sexo', text: 'Existe alguma coisa que você gostaria que acontecesse com mais frequência depois dos nossos momentos íntimos?' },
  { id: 'c-e-99', intensity: 'erotico', category: 'Segurança emocional', text: 'O que eu posso fazer para você sentir que pode contar qualquer desejo ou limite sexual sem medo de julgamento?' },
  { id: 'c-e-100', intensity: 'erotico', category: 'Intimidade', text: 'Se pudéssemos aprender juntos uma coisa nova sobre nossa sexualidade neste ano, o que você gostaria que fosse?' }
];
