export const extraHotCoupleQuestions = [
  { id: 'c-q-15', intensity: 'quente', category: 'Fantasias', text: 'Qual fantasia adulta você teria curiosidade de explorar comigo, desde que nós dois estivéssemos confortáveis?' },
  { id: 'c-q-16', intensity: 'quente', category: 'Desejo', text: 'Você prefere tomar a iniciativa ou perceber que eu tomei a iniciativa primeiro?' },
  { id: 'c-q-17', intensity: 'quente', category: 'Provocação', text: 'Que tipo de provocação aumenta mais sua expectativa antes de um momento íntimo?' },
  { id: 'c-q-18', intensity: 'quente', category: 'Clima', text: 'Você prefere meia-luz, escuridão ou um ambiente mais iluminado quando quer entrar no clima?' },
  { id: 'c-q-19', intensity: 'quente', category: 'Desejo', text: 'Qual roupa minha mais desperta sua atração — e por quê?' },
  { id: 'c-q-20', intensity: 'quente', category: 'Provocação', text: 'Qual tipo de mensagem minha durante o dia faria você passar horas pensando no que pode acontecer depois?' },
  { id: 'c-q-21', intensity: 'quente', category: 'Fantasias', text: 'Você toparia uma brincadeira em que um de nós fica de olhos vendados, com tudo combinado antes?' },
  { id: 'c-q-22', intensity: 'quente', category: 'Comunicação', text: 'Existe algo que você sempre teve vontade de me pedir na intimidade, mas ainda não encontrou o momento certo?' },
  { id: 'c-q-23', intensity: 'quente', category: 'Desejo', text: 'O que eu faço antes mesmo de te tocar que já aumenta sua vontade?' },
  { id: 'c-q-24', intensity: 'quente', category: 'Provocação', text: 'Você gosta mais de prolongar a tensão e a expectativa ou prefere espontaneidade sem muita preparação?' },
  { id: 'c-q-25', intensity: 'quente', category: 'Cenários', text: 'Qual lugar da casa você acha mais tentador para quebrar a rotina e criar um clima diferente?' },
  { id: 'c-q-26', intensity: 'quente', category: 'Cenários', text: 'Se tivéssemos uma noite inteira em um hotel só para nós, o que tornaria essa noite inesquecível?' },
  { id: 'c-q-27', intensity: 'quente', category: 'Fantasias', text: 'Existe algum personagem, papel ou cenário de sedução que você teria curiosidade de interpretar comigo?' },
  { id: 'c-q-28', intensity: 'quente', category: 'Comunicação', text: 'Você prefere silêncio e clima ou conversa provocante quando a tensão entre nós aumenta?' },
  { id: 'c-q-29', intensity: 'quente', category: 'Desejo', text: 'Qual elogio mais direto faria você se sentir imediatamente desejado(a)?' },
  { id: 'c-q-30', intensity: 'quente', category: 'Provocação', text: 'Se eu pudesse te provocar durante alguns minutos sem você poder retribuir imediatamente, isso seria divertido para você?' },
  { id: 'c-q-31', intensity: 'quente', category: 'Limites', text: 'Qual limite é importante para você que eu sempre respeite, mesmo quando estivermos experimentando algo novo?' },
  { id: 'c-q-32', intensity: 'quente', category: 'Fantasias', text: 'Que tipo de novidade você gostaria de experimentar uma vez só para descobrir se gosta?' },
  { id: 'c-q-33', intensity: 'quente', category: 'Desejo', text: 'Você gosta mais de sentir que está sendo conquistado(a) ou de perceber que está me conquistando?' },
  { id: 'c-q-34', intensity: 'quente', category: 'Provocação', text: 'Qual gesto discreto em público poderia criar uma tensão gostosa entre nós sem ninguém perceber?' },
  { id: 'c-q-35', intensity: 'quente', category: 'Clima', text: 'Qual combinação de música, iluminação e ambiente mais ajuda você a entrar no clima?' },
  { id: 'c-q-36', intensity: 'quente', category: 'Comunicação', text: 'O que você gostaria que eu perguntasse com mais naturalidade sobre suas preferências íntimas?' },
  { id: 'c-q-37', intensity: 'quente', category: 'Fantasias', text: 'Você toparia uma noite em que cada um prepara uma surpresa sensual para o outro, sem revelar antes?' },
  { id: 'c-q-38', intensity: 'quente', category: 'Desejo', text: 'Qual é a diferença, para você, entre achar alguém bonito e realmente sentir desejo por essa pessoa?' },
  { id: 'c-q-39', intensity: 'quente', category: 'Provocação', text: 'O que te provoca mais: antecipação, surpresa ou sentir que você está no controle da situação?' },
  { id: 'c-q-40', intensity: 'quente', category: 'Cenários', text: 'Qual viagem ou destino teria o cenário perfeito para uma escapada mais ousada a dois?' },
  { id: 'c-q-41', intensity: 'quente', category: 'Fantasias', text: 'Se criássemos um desafio de sedução entre nós, qual regra deixaria a brincadeira mais interessante?' },
  { id: 'c-q-42', intensity: 'quente', category: 'Comunicação', text: 'Tem alguma palavra, frase ou tipo de elogio que aumenta muito sua confiança em um momento íntimo?' },
  { id: 'c-q-43', intensity: 'quente', category: 'Desejo', text: 'Qual lembrança nossa teve uma tensão ou química que você gostaria de recriar?' },
  { id: 'c-q-44', intensity: 'quente', category: 'Limites', text: 'Existe algo que você tem certeza de que não gostaria de experimentar e prefere deixar claro desde já?' },
  { id: 'c-q-45', intensity: 'quente', category: 'Provocação', text: 'Você gostaria de receber uma mensagem minha dizendo exatamente o que estou pensando sobre você naquele momento?' },
  { id: 'c-q-46', intensity: 'quente', category: 'Cenários', text: 'Você prefere um momento íntimo totalmente planejado ou algo que começa de forma inesperada?' },
  { id: 'c-q-47', intensity: 'quente', category: 'Desejo', text: 'O que faz você se sentir mais confiante e à vontade para demonstrar desejo sem vergonha?' },
  { id: 'c-q-48', intensity: 'quente', category: 'Fantasias', text: 'Você toparia escolher uma roupa ou visual específico para eu usar em uma noite a dois?' },
  { id: 'c-q-49', intensity: 'quente', category: 'Comunicação', text: 'Quando você quer algo diferente na intimidade, qual seria a melhor forma de eu perceber ou perguntar?' },
  { id: 'c-q-50', intensity: 'quente', category: 'Provocação', text: 'Qual parte do jogo de sedução você mais gosta: os olhares, as palavras, a aproximação ou a surpresa?' }
];
